#ifndef HVOS_SCHEDULER_TASK__STATE_H
#define HVOS_SCHEDULER_TASK__STATE_H

#define TASK_STATE_RUNNING				0
#define TASK_STATE_WAITING				1
#define TASK_STATE_DEAD					2
#define TASK_STATE_BLOCKED_ON_KEYBOARD 10

#endif