#ifndef HVOS_SCHEDULER_TASK__STATE_H
#define HVOS_SCHEDULER_TASK__STATE_H

#define STATE_NEW			0
#define STATE_READY			1
#define STATE_RUNNING		2
#define STATE_WAITING		3
#define STATE_DEAD			4
#define STATE_SLEEPING		5

#endif